import React from 'react'
import Head from 'next/head'

interface Props {
  children: React.ReactNode
}

const Layout: React.FC<Props> = ({ children }) => {
  const year = new Date().getFullYear()
  return (
    <>
      <Head>
        <title>GPT Translator</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {children}
      {/* create a footer  */}
      <footer className='static md:absolute w-full bottom-0 flex justify-center items-center h-10 font-inter bg-gray-800 text-white'>
        <p>💖️ {year} Made with love Andrés Florez</p>
      </footer>
    </>
  )
}

export default Layout
